import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/main-layout";

const InterSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const InterMono = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const PoppinsSans = Poppins({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const PoppinsMono = Poppins({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Dua App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${InterSans.variable} ${InterMono.variable} antialiased`}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
